#!/bin/bash

echo "Compiling..."

echo "gcc -o otp_enc_d src/otp_enc_d.c -g"
gcc -o otp_enc_d src/otp_enc_d.c -g

echo "gcc -o otp_enc src/otp_enc.c -g"
gcc -o otp_enc src/otp_enc.c -g

echo "gcc -o otp_enc_d src/otp_dec_d.c -g"
gcc -o otp_dec_d src/otp_dec_d.c -g

echo "gcc -o otp_enc src/otp_dec.c -g"
gcc -o otp_dec src/otp_dec.c -g

echo "gcc -o keygen src/keygen.c -g"
gcc -o keygen src/keygen.c -g

echo "Compiled!"
